---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ofisu
  name: ofisu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ofisu
  template:
    metadata:
      labels:
        app: ofisu
    spec:
      containers:
        - name: ofisu
          resources:
            requests:
              cpu: "250m"
              memory: "245Mi"
            limits:
              cpu: "1"
              memory: "1G"
          command:
            - ofisu
          args:
            - discord-manager
            - "--offices=/usr/local/share/ofisu/offices.d"
          envFrom:
            - secretRef:
                name: ofisu-env
          volumeMounts:
            - name: offices
              mountPath: "/usr/local/share/ofisu/offices.d"
              readOnly: true
          # TODO: pin this and enable automated deploys
          image: us.gcr.io/kizuna-188702/github.com/austinpray/ofisu:PLACEHOLDER
          imagePullPolicy: Always
      volumes:
        - name: offices
          configMap:
            name: offices
      restartPolicy: Always
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ofisu-rec-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: ofisu
  updatePolicy:
    updateMode: "Off"
